<?php
/** @var $this Shift4_Payment_Block_Payment_Form_Cc */
?>
<?php
$_code = $this->getMethodCode();
$_formMessage = $this->getPartialAuthorizationFormMessage();
?>
<?php $_isPartialAuthorization = $this->isPartialAuthorization(); ?>

<?php if ($_isPartialAuthorization || $_formMessage): ?>
    <div class="form-list" id="payment_form_<?php echo $_code; ?>_before" style="display:none;">
        <?php if ($_formMessage): ?>
            <?php echo $this->showNoticeMessage($_formMessage) ?>
        <?php endif; ?>

        <?php if ($this->isPartialAuthorization()): ?>
            <?php echo $this->getChildHtml('cards') ?>
            <div class="release-amounts" style="margin: 1.5em 0;">
                <button class="button" type="button" id="payment-button-cancel"><span><span>Cancel</span></span></button>
                <span><?php echo $this->__('To cancel your purchase, click Cancel') ?></span>
            </div>
            <?php echo $this->showNoticeMessage($this->__('Please enter another credit card number to complete your purchase.')) ?>

            <script type="text/javascript">
                //<![CDATA[
                var cancelButtonId = 'payment-button-cancel';
                var cancelButton = $(cancelButtonId);
                cancelButton.click = null;
                Event.observe(cancelButton, 'click', cancelPaymentAuthorizations);

                function cancelPaymentAuthorizations(event, hideConfirm) {
                    if (!hideConfirm && !confirm('<?php echo $this->getCancelConfirmationMessage() ?>')) {
                        return;
                    }
                    $('cancel-please-wait').show();
                    new Ajax.Request('<?php echo $this->getCancelUrl() ?>', {
                        onSuccess: function(transport) {
                            $('cancel-please-wait').hide();
                            try {
                                response = eval('(' + transport.responseText + ')');
                            } catch (e) {
                                response = {};
                            }
                            if (response.success) {
                                $(cancelButtonId).remove();
                                $('checkout-payment-method-load').update(response.update_html);
                                if (checkout) {
                                    checkout.reloadProgressBlock();
                                }
                            } else {
                                var msg = response.error_message;
                                if (msg) {
                                    alert(msg);
                                }
                            }
                        },
                        parameters: {method_code: '<?php echo $_code; ?>'}
                    });
                }

        <?php if ($_message = $this->getPartialAuthorizationConfirmationMessage()): ?>
                    if (!confirm('<?php echo $_message ?>')) {
                        cancelPaymentAuthorizations(true, true);
                    }

        <?php endif; ?>
                $j("#checkout-payment-method-load input[type='radio']").click(function() {
                    var method = $j(this).val();
                    if (method != '<?php echo $_code; ?>') {
                        // check if user already have some authorized amount
                        alert('Yes');
                        $j(this).attr('checked', false);

                        return false;
                    }
                });
                //]]>
            </script>
            <span id="cancel-please-wait" class="please-wait" style="display:none">
                <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="" class="v-middle" /> <?php echo $this->__('Processing...') ?>
            </span>
        <?php endif; ?>
    </div>
<?php endif; ?>
<?php echo $this->getChildHtml('method_form_block') ?>
